### ISSUE TITLE
Allow identification of Ubuntu Touch device in Google Analytics

### ISSUE THREAD

**Issue by nhoizey** [esviji/esviji-ubuntu-touch#1]
@cibersheep the query string in the `start_url` attribute of the `manifest.webmaniefst` allows me to know if people use the game from a browser, installed as a PWA, or as an Android app.

Is the manifest also used by Ubuntu Touch apps?

**Comment by cibersheep** [comment]
Oh, I see. As far as I know, no, it's not used.
How I should proceed here?

**Comment by nhoizey** [comment]
Ok, so I think I have to change how it works and use a JS call instead.

I'll think about it and let you know.

**Comment by cibersheep** [comment]
Sure!

**Comment by nhoizey** [comment]
I guess you build the app with `npm run build` and then put the result in your `www` folder, is that right?

With this commit:
https://github.com/esviji/esviji/commit/e9b6a9f097554c7ea54548480e3f3eef2d9ac1f4

You can now change 'Web' to 'Ubuntu Touch' in `nunjucks.config.js` before running the build, and it should work. It injects this value in the "About" screen, and the JavaScript get thee value to send it to Google Analytics, like for the version.

**Comment by cibersheep** [comment]
Ok. [That](https://github.com/esviji/esviji-ubuntu-touch/commit/7af6cac804f434e014764cf8e4524992c905a36b) should be it :)
I also made the app icon svg (more than appropriate :) )

**Comment by nhoizey** [comment]
Awesome! 👍
