### ISSUE TITLE
Clean package from useless files

### ISSUE THREAD

**Issue by nhoizey** [esviji/esviji-ubuntu-touch#2]
@cibersheep do you think it would be preferable to remove some files that are probably not used by the Ubuntu Touch version?

- `.well-known`
- `wow`
- `*.map`
- `humans.txt`
- `robots.txt`
- `manifest.webmanifest`?
- `service-worker.js`?
- `privacy-policy.html`
- `terms-and-conditions.html`
- `tutorial.svg` (obsolete, I'll remove it from the source)

**Comment by cibersheep** [comment]
I didn't know if I could remove them. Maybe I'll leave the privacy and terms in the package.
Also, would that be ok to remove some app icons as well?
I need to do a script for that :D

**Comment by nhoizey** [comment]
I guess people installing the Ubuntu Touch package don't have access to what's inside, do they?

Every thing that is useless for people installing this can be removed.

**Comment by cibersheep** [comment]
It is accessible as the click is unpacked in the system. And UT users tend to check the code :)
I think might be a good idea to leave the licencing.

Edit: first clean up pushed

**Comment by nhoizey** [comment]
Ok, it looks perfect know! 👍

**Comment by cibersheep** [comment]
Are we ready to rock? (aka: do I publish it?)

**Comment by nhoizey** [comment]
@cibersheep YES! 🎉

Sorry, I was not clear enough… 😅

**Comment by cibersheep** [comment]
Don't be sorry... just double checking... 3, 2, ...

https://open-store.io/app/esviji.cibersheep
