### ISSUE TITLE
Game pauze

### ISSUE THREAD

**Issue by ghost** [esviji/esviji-ubuntu-touch#4]
When i pauze the game and exit i can resume it, but when you complete exits the game you can not resume it anymore you need to start over again, i dont know if that's the correct way ?

**Comment by cibersheep** [comment]
Esviji should resume where you left it.

I see this is not working, when reopen app (also happens on website in Morph) it will restart from level 1. But on my test app, I'm in a loop at the end of level 11... even if I completed and riched level 12 mmmhhmmm

**Comment by nhoizey** [comment]
esviji uses localStorage in the browser to store the game status, to be able to resume an existing play.

With the issue in #3, it looks like localStorage doesn't work here.

**Comment by cibersheep** [comment]
Pushed a new version, I used a webview which uses LocalStorage properly :)
Fixed
